# Configurações de Conexão Geral
SUPABASE_URL = "https://zydjmwrkwyaleteyblft.supabase.co"
SUPABASE_KEY = "sb_publishable_5zRtd1Bhxd6XKz56RpbwCA_uZnZExYg"

# Mapeamento de Schemas para o Monólito Modular
[SCHEMAS]
AUTENTICACAO = "public"     
DESAFIOS     = "public"     
ACADEMICO    = "public"     
GAMIFICACAO  = "public"    